CREATE DATABASE  IF NOT EXISTS `server_bike` /*!40100 DEFAULT CHARACTER SET utf8 COLLATE utf8_bin */;
USE `server_bike`;
-- -----------------------------------------------------
-- Table `ESTACAO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ESTACAO` ;

CREATE TABLE IF NOT EXISTS `ESTACAO` (
  `ID_ESTACAO` INT NOT NULL,
  `NOME` VARCHAR(45) NOT NULL,
  `LOCALIZACAO` VARCHAR(4000) NOT NULL,
  PRIMARY KEY (`ID_ESTACAO`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `server_bike`.`USUARIO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `server_bike`.`USUARIO` ;

CREATE TABLE IF NOT EXISTS `server_bike`.`USUARIO` (
  `ID_USUARIO` INT(6) NOT NULL AUTO_INCREMENT,
  `NOME` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NOT NULL,
  `SOBRENOME` VARCHAR(150) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NOT NULL,
  `TELEFONE` VARCHAR(16) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NOT NULL,
  `EMAIL` VARCHAR(150) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NOT NULL,
  `SENHA` VARCHAR(40) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NOT NULL,
  PRIMARY KEY (`ID_USUARIO`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `USUARIO_ESTACAO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `USUARIO_ESTACAO` ;

CREATE TABLE IF NOT EXISTS `USUARIO_ESTACAO` (
  `ID_USUARIO` INT NOT NULL,
  `USUARIO_ID_USUARIO` INT(6) NOT NULL,
  `ESTACAO_ID_ESTACAO` INT NOT NULL,
  `HORA_INICIO` DATE NOT NULL,
  `HORA_FIM` DATE NULL,
  `CARGA_RESTANTE` FLOAT NULL,
  PRIMARY KEY (`ID_USUARIO`),
  INDEX `fk_USUARIO_ESTACAO_USUARIO_idx` (`USUARIO_ID_USUARIO` ASC),
  INDEX `fk_USUARIO_ESTACAO_ESTACAO1_idx` (`ESTACAO_ID_ESTACAO` ASC),
  CONSTRAINT `fk_USUARIO_ESTACAO_USUARIO`
    FOREIGN KEY (`USUARIO_ID_USUARIO`)
    REFERENCES `server_bike`.`USUARIO` (`ID_USUARIO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_USUARIO_ESTACAO_ESTACAO1`
    FOREIGN KEY (`ESTACAO_ID_ESTACAO`)
    REFERENCES `ESTACAO` (`ID_ESTACAO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `server_bike` ;