DROP SCHEMA server_bike;
CREATE DATABASE  IF NOT EXISTS `server_bike` /*!40100 DEFAULT CHARACTER SET utf8 COLLATE utf8_bin */;
USE `server_bike`;

--
-- Table structure for table `BATERIA`
--

DROP TABLE IF EXISTS `BATERIA`;
CREATE TABLE `BATERIA` (
  `idBATERIA` int(11) NOT NULL AUTO_INCREMENT,
  `CORRENTE` varchar(45) COLLATE utf8_bin DEFAULT NULL,
  PRIMARY KEY (`idBATERIA`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8 COLLATE=utf8_bin;



INSERT INTO `BATERIA` VALUES (1,'220');

--
-- Table structure for table `ESTACAO`
--

DROP TABLE IF EXISTS `ESTACAO`;
CREATE TABLE `ESTACAO` (
  `ID_ESTACAO` int(11) NOT NULL AUTO_INCREMENT,
  `NOME` varchar(45) COLLATE utf8_bin NOT NULL,
  `LOCALIZACAO` varchar(4000) COLLATE utf8_bin NOT NULL,
  PRIMARY KEY (`ID_ESTACAO`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8 COLLATE=utf8_bin;


INSERT INTO `ESTACAO` VALUES (1,'piloto','');

--
-- Table structure for table `SOLICITACAO`
--

DROP TABLE IF EXISTS `SOLICITACAO`;
CREATE TABLE `SOLICITACAO` (
  `idSOLICITACAO` int(11) NOT NULL AUTO_INCREMENT,
  `DATA_ABERTURA` datetime NOT NULL,
  `DATA_FECHAMENTO` datetime DEFAULT NULL,
  `ID_ARDUINO` int(11) DEFAULT NULL,
  `ID_TIPO` int(11) DEFAULT NULL,
  `FLAG_ERRO` int(11) DEFAULT NULL,
  PRIMARY KEY (`idSOLICITACAO`)
) ENGINE=InnoDB AUTO_INCREMENT=41 DEFAULT CHARSET=utf8 COLLATE=utf8_bin;


--
-- Table structure for table `USUARIO`
--

DROP TABLE IF EXISTS `USUARIO`;
CREATE TABLE `USUARIO` (
  `ID_USUARIO` int(6) NOT NULL AUTO_INCREMENT,
  `NOME` varchar(45) COLLATE utf8_bin NOT NULL,
  `SOBRENOME` varchar(150) COLLATE utf8_bin NOT NULL,
  `TELEFONE` varchar(16) COLLATE utf8_bin NOT NULL,
  `EMAIL` varchar(150) COLLATE utf8_bin NOT NULL,
  `SENHA` varchar(40) COLLATE utf8_bin NOT NULL,
  PRIMARY KEY (`ID_USUARIO`)
) ENGINE=InnoDB AUTO_INCREMENT=28 DEFAULT CHARSET=utf8 COLLATE=utf8_bin;


--
-- Table structure for table `USUARIO_ESTACAO`
--

DROP TABLE IF EXISTS `USUARIO_ESTACAO`;
CREATE TABLE `USUARIO_ESTACAO` (
  `ID_USUARIO` int(11) NOT NULL AUTO_INCREMENT,
  `USUARIO_ID_USUARIO` int(6) NOT NULL,
  `ESTACAO_ID_ESTACAO` int(11) NOT NULL,
  `HORA_INICIO` datetime NOT NULL,
  `HORA_FIM` datetime DEFAULT NULL,
  `CARGA_RESTANTE` float DEFAULT NULL,
  PRIMARY KEY (`ID_USUARIO`),
  KEY `fk_USUARIO_ESTACAO_USUARIO_idx` (`USUARIO_ID_USUARIO`),
  KEY `fk_USUARIO_ESTACAO_ESTACAO1_idx` (`ESTACAO_ID_ESTACAO`),
  CONSTRAINT `fk_USUARIO_ESTACAO_ESTACAO1` FOREIGN KEY (`ESTACAO_ID_ESTACAO`) REFERENCES `ESTACAO` (`ID_ESTACAO`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_USUARIO_ESTACAO_USUARIO` FOREIGN KEY (`USUARIO_ID_USUARIO`) REFERENCES `USUARIO` (`ID_USUARIO`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=10 DEFAULT CHARSET=utf8 COLLATE=utf8_bin;