-- MySQL Script generated by MySQL Workbench
-- Fri Jun  5 16:43:45 2015
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema server_bike
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `server_bike` ;
CREATE SCHEMA IF NOT EXISTS `server_bike` DEFAULT CHARACTER SET utf8 COLLATE utf8_bin ;
USE `server_bike` ;

-- -----------------------------------------------------
-- Table `server_bike`.`ESTACAO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `server_bike`.`ESTACAO` ;

CREATE TABLE IF NOT EXISTS `server_bike`.`ESTACAO` (
  `ID_ESTACAO` INT NOT NULL AUTO_INCREMENT,
  `NOME` VARCHAR(45) NOT NULL,
  `LOCALIZACAO` VARCHAR(4000) NOT NULL,
  PRIMARY KEY (`ID_ESTACAO`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `server_bike`.`USUARIO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `server_bike`.`USUARIO` ;

CREATE TABLE IF NOT EXISTS `server_bike`.`USUARIO` (
  `ID_USUARIO` INT(6) NOT NULL AUTO_INCREMENT,
  `NOME` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NOT NULL,
  `SOBRENOME` VARCHAR(150) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NOT NULL,
  `TELEFONE` VARCHAR(16) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NOT NULL,
  `EMAIL` VARCHAR(150) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NOT NULL,
  `SENHA` VARCHAR(40) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NOT NULL,
  PRIMARY KEY (`ID_USUARIO`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `server_bike`.`USUARIO_ESTACAO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `server_bike`.`USUARIO_ESTACAO` ;

CREATE TABLE IF NOT EXISTS `server_bike`.`USUARIO_ESTACAO` (
  `ID_USUARIO` INT NOT NULL AUTO_INCREMENT,
  `USUARIO_ID_USUARIO` INT(6) NOT NULL,
  `ESTACAO_ID_ESTACAO` INT NOT NULL,
  `HORA_INICIO` DATETIME NOT NULL,
  `HORA_FIM` DATETIME NULL DEFAULT NULL,
  `CARGA_RESTANTE` FLOAT NULL DEFAULT NULL,
  PRIMARY KEY (`ID_USUARIO`),
  INDEX `fk_USUARIO_ESTACAO_USUARIO_idx` (`USUARIO_ID_USUARIO` ASC),
  INDEX `fk_USUARIO_ESTACAO_ESTACAO1_idx` (`ESTACAO_ID_ESTACAO` ASC),
  CONSTRAINT `fk_USUARIO_ESTACAO_USUARIO`
    FOREIGN KEY (`USUARIO_ID_USUARIO`)
    REFERENCES `server_bike`.`USUARIO` (`ID_USUARIO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_USUARIO_ESTACAO_ESTACAO1`
    FOREIGN KEY (`ESTACAO_ID_ESTACAO`)
    REFERENCES `server_bike`.`ESTACAO` (`ID_ESTACAO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `server_bike`.`SOLICITACAO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `server_bike`.`SOLICITACAO` ;

CREATE TABLE IF NOT EXISTS `server_bike`.`SOLICITACAO` (
  `idSOLICITACAO` INT NOT NULL AUTO_INCREMENT,
  `DATA_ABERTURA` DATETIME NOT NULL,
  `DATA_FECHAMENTO` DATETIME NULL,
  `ID_ARDUINO` INT NULL,
  `ID_TIPO` INT NULL,
  `FLAG_ERRO` INT NULL,
  PRIMARY KEY (`idSOLICITACAO`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
